Traceback (most recent call last):
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\sandr\anaconda3\envs\renv\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# GrÃ¡fico de causalidad

sprinkler = CausalGraphicalModel(nodes=["Go â†“","DA â†“","Y â†“"],
                                 edges=[("Go â†“","DA â†“"), ("DA â†“","Y â†“")])
sprinkler.draw()

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_19060/1648444016.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# GrÃ¡fico de causalidad[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m sprinkler = CausalGraphicalModel(nodes=["Go â†“","DA â†“","Y â†“"],
[0m[0;32m      4[0m                                  edges=[("Go â†“","DA â†“"), ("DA â†“","Y â†“")])
[0;32m      5[0m [0msprinkler[0m[1;33m.[0m[0mdraw[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'CausalGraphicalModel' is not defined
NameError: name 'CausalGraphicalModel' is not defined

